vae:
  input_adata_path: "adata_vae.h5ad"
  output_adata_path: "adata_vae_clustered.h5ad"

  embedding_key: "X_vae"
  leiden_key: "leiden"

  n_neighbors: 200 #15
  resolution: 0.1 #3 #0.5, major

  reference_label: "major" 
  # "minor" resolution de 3