data_path: "Dataset/raw/matrix.mtx"

n_top_genes: 5000
batch_size: 64
latent_dim: 30
epochs: 40
learning_rate: 0.001
dropout_rate: 0.2
mask_rate: 0.3

output_obsm_key: "X_dae"
output_adata_path: "adata_dae.h5ad"
output_model_path: "dae_model.pt"

device: "cpu"
