from pathlib import Path
import numpy as np
import pandas as pd
import scanpy as sc
import yaml


def get_major_type(signature):

    if signature.startswith("Basal"):
        return "Basal"

    if signature.startswith("Secretory"):
        return "Secretory"

    if signature.startswith("Ciliated"):
        return "Ciliated"

    return signature


def load_signatures(csv_path, signature_column):

    data = pd.read_csv(csv_path)

    if signature_column not in data.columns:
        raise ValueError(
            f"Column '{signature_column}' not found. "
            f"Available columns: {data.columns.tolist()}"
        )

    gene_columns = [
        column
        for column in data.columns
        if column.startswith("gene_")
    ]

    gene_columns = sorted(gene_columns,key=lambda column: int(column.split("_")[-1]))

    signatures = {}

    for _, row in data.iterrows():

        signature = str(row[signature_column]).strip()

        genes = [
            str(row[column]).strip()
            for column in gene_columns
            if pd.notna(row[column])
        ]

        genes = list(dict.fromkeys(genes))

        if genes:
            signatures[signature] = genes

    return signatures


def run_scoring(config_path):

    with open(config_path, "r", encoding="utf-8") as file:
        config = yaml.safe_load(file)

    adata_path = config["adata_path"]
    signatures_path = config["signatures_path"]
    signature_column = config["signature_column"]
    annotation_level = config["annotation_level"]
    cluster_key = config["cluster_key"]

    minimum_genes = config.get("minimum_genes", 3)
    random_state = config.get("random_state", 42)

    output_adata = Path(config["output_adata_path"])
    output_scores = Path(config["output_cluster_scores_path"])
    output_assignments = Path(config["output_assignments_path"])
    output_coverage = Path(
        config["output_signature_coverage_path"]
    )

    for path in [
        output_adata,
        output_scores,
        output_assignments,
        output_coverage,
    ]:
        path.parent.mkdir(parents=True,exist_ok=True)

    # Load clustered AnnData
    print(f"Loading AnnData: {adata_path}")

    adata = sc.read_h5ad(adata_path)

    if cluster_key not in adata.obs.columns:
        raise KeyError(
            f"Cluster column '{cluster_key}' not found. "
            f"Available columns: {adata.obs.columns.tolist()}"
        )

    # Load signatures
    signatures = load_signatures(signatures_path,signature_column)

    print(f"{len(signatures)} signatures loaded.")

    # Match CSV genes with AnnData genes, ignoring case
    gene_mapping = {
        str(gene).upper(): str(gene)
        for gene in adata.var_names
    }

    used_signatures = {}
    coverage_rows = []

    # Calculate one score per signature and cell
    for signature, original_genes in signatures.items():

        available_genes = [
            gene_mapping[gene.upper()]
            for gene in original_genes
            if gene.upper() in gene_mapping
        ]

        available_genes = list(
            dict.fromkeys(available_genes)
        )

        coverage_rows.append(
            {
                "signature": signature,
                "original_genes": len(original_genes),
                "available_genes": len(available_genes),
                "coverage": (
                    len(available_genes)
                    / len(original_genes)
                ),
                "used_for_scoring": (
                    len(available_genes)
                    >= minimum_genes
                ),
            }
        )

        print(
            f"{signature}: "
            f"{len(available_genes)}/"
            f"{len(original_genes)} genes available"
        )

        if len(available_genes) < minimum_genes:
            print(
                f"Skipping {signature}: "
                "not enough genes."
            )
            continue

        sc.tl.score_genes(
            adata,
            gene_list=available_genes,
            score_name=f"{signature}_score",
            ctrl_size=min(50, len(available_genes)),
            n_bins=25,
            random_state=random_state,
            use_raw=False,
        )

        used_signatures[signature] = get_major_type(
            signature
        )

    if not used_signatures:
        raise ValueError(
            "No signature had enough available genes."
        )

    # Columns generated by score_genes
    score_columns = [
        f"{signature}_score"
        for signature in used_signatures
    ]

    # Average every score inside each cluster
    cluster_scores = (
        adata.obs
        .groupby(
            cluster_key,
            observed=True,
        )[score_columns]
        .mean()
    )

    # Select the signature with the highest average score
    best_columns = cluster_scores.idxmax(axis=1)

    cluster_scores["assigned_signature"] = (
        best_columns
        .str.replace(
            "_score",
            "",
            regex=False,
        )
    )

    if annotation_level == "major":
        cluster_scores["assigned_major_type"] = (
            cluster_scores["assigned_signature"]
        )
    else:
        cluster_scores["assigned_major_type"] = (
            cluster_scores["assigned_signature"]
            .map(used_signatures)
        )

    # Calculate difference between best and second-best score
    sorted_scores = np.sort(
        cluster_scores[score_columns].to_numpy(),
        axis=1,
    )

    cluster_scores["best_score"] = sorted_scores[:, -1]

    if len(score_columns) > 1:
        cluster_scores["score_margin"] = (
            sorted_scores[:, -1]
            - sorted_scores[:, -2]
        )
    else:
        cluster_scores["score_margin"] = np.nan

    # Add cluster assignments to every cell
    signature_mapping = (
        cluster_scores["assigned_signature"]
        .astype(str)
        .to_dict()
    )

    major_mapping = (
        cluster_scores["assigned_major_type"]
        .astype(str)
        .to_dict()
    )

    cell_clusters = adata.obs[
        cluster_key
    ].astype(str)

    signature_mapping = {
        str(cluster): value
        for cluster, value in signature_mapping.items()
    }

    major_mapping = {
        str(cluster): value
        for cluster, value in major_mapping.items()
    }

    adata.obs["predicted_signature"] = (
        cell_clusters.map(signature_mapping)
    )

    adata.obs["predicted_major_cell_type"] = (
        cell_clusters.map(major_mapping)
    )

    assignments = cluster_scores[
        [
            "assigned_signature",
            "assigned_major_type",
            "best_score",
            "score_margin",
        ]
    ]

    # Save results
    pd.DataFrame(coverage_rows).to_csv(
        output_coverage,
        index=False,
    )

    cluster_scores.to_csv(output_scores)
    assignments.to_csv(output_assignments)
    adata.write_h5ad(output_adata)

    print("\nFinal assignments:")
    print(assignments)

    print("\nFiles saved:")
    print(output_adata)
    print(output_scores)
    print(output_assignments)
    print(output_coverage)